# Generated by Django 5.1.6 on 2025-02-25 03:45

import django.db.models.deletion
import django.utils.timezone
import production.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工序名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工序编码')),
                ('daily_capacity', models.IntegerField(verbose_name='日产能')),
                ('is_bottleneck', models.BooleanField(default=False, verbose_name='是否瓶颈工序')),
                ('sequence', models.IntegerField(verbose_name='序号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('status', models.CharField(choices=[('normal', '正常'), ('maintenance', '维护中'), ('malfunction', '故障'), ('scrapped', '报废')], default='normal', max_length=20, verbose_name='设备状态')),
                ('daily_capacity', models.IntegerField(verbose_name='日产能')),
                ('purchase_date', models.DateField(verbose_name='购入日期')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.processstep', verbose_name='所属工序')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='生产单号')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划数量')),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='完成数量')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='计划开始日期')),
                ('end_date', models.DateField(default=production.models.get_default_end_date, verbose_name='计划完成日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('status', models.CharField(choices=[('pending', '待生产'), ('material_ready', '备料完成'), ('in_production', '生产中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='进度(%)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('estimated_completion_time', models.DateTimeField(verbose_name='预计完成时间')),
                ('actual_production_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际生产成本')),
                ('quality_check_status', models.CharField(choices=[('pending', '待检'), ('passed', '合格'), ('failed', '不合格')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '生产订单',
                'verbose_name_plural': '生产订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='使用数量')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.materialbatch', verbose_name='材料批次')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_used', to='production.productionorder', verbose_name='生产单')),
            ],
            options={
                'verbose_name': '生产用料',
                'verbose_name_plural': '生产用料',
            },
        ),
        migrations.CreateModel(
            name='ProcessSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('planned_end_time', models.DateTimeField(verbose_name='计划结束时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('delayed', '延迟')], default='pending', max_length=20, verbose_name='状态')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.equipment', verbose_name='设备')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.processstep', verbose_name='工序')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_schedules', to='production.productionorder', verbose_name='生产订单')),
            ],
            options={
                'verbose_name': '工序排程',
                'verbose_name_plural': '工序排程',
                'ordering': ['planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now, verbose_name='记录日期')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='本次数量')),
                ('accumulated_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='累计数量')),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='进度(%)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('can_edit', models.BooleanField(default=True, verbose_name='可修改')),
                ('actual_efficiency', models.DecimalField(decimal_places=2, help_text='实际完成数量/计划数量的百分比', max_digits=5, verbose_name='实际效率')),
                ('delay_reason', models.TextField(blank=True, null=True, verbose_name='延迟原因')),
                ('quality_issues', models.IntegerField(default=0, verbose_name='质量问题数量')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='production.productionorder', verbose_name='生产订单')),
            ],
            options={
                'verbose_name': '生产进度',
                'verbose_name_plural': '生产进度',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='需求数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='实际领用数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='材料')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='production.productionorder', verbose_name='生产订单')),
            ],
            options={
                'verbose_name': '材料需求',
                'verbose_name_plural': '材料需求',
                'unique_together': {('production_order', 'material')},
            },
        ),
    ]
