# Generated by Django 5.1.6 on 2025-03-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('production', '0002_init_process_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='orders.order', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quality_check_status',
            field=models.CharField(choices=[('pending', '待检'), ('passed', '合格'), ('failed', '不合格')], default='pending', max_length=20, verbose_name='质检状态'),
        ),
    ]
