# Generated by Django 5.1.6 on 2025-03-04 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('production', '0004_alter_productionorder_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='orders.order', verbose_name='销售订单'),
        ),
    ]
