# Generated by Django 5.1.6 on 2025-02-25 03:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='材料编码')),
                ('name', models.CharField(max_length=100, verbose_name='材料名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='尺寸')),
                ('supply_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='来料方式')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='库存')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='最小库存')),
                ('warning_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='预警库存')),
                ('max_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='最大库存')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最近采购价')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待入库'), ('received', '已入库'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='库存数量')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='最小库存')),
                ('warning_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='预警库存')),
                ('max_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='最大库存')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='盘点单号')),
                ('inventory_date', models.DateField(verbose_name='盘点日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('adjustment_type', models.CharField(choices=[('profit', '盘盈'), ('loss', '盘亏'), ('normal', '正常')], default='normal', max_length=20, verbose_name='盘点类型')),
                ('total_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='差异总量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'ordering': ['-inventory_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='系统数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际数量')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='差异数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory', verbose_name='盘点单')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '盘点明细',
                'verbose_name_plural': '盘点明细',
            },
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('production_date', models.DateField(default='2025-01-01', verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='初始数量')),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='剩余数量')),
                ('status', models.CharField(choices=[('normal', '正常'), ('expired', '已过期'), ('depleted', '已耗尽')], default='normal', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.material', verbose_name='材料')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_batches', to='inventory.materialpurchase', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '材料批次',
                'verbose_name_plural': '材料批次',
            },
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2025-01-01', verbose_name='日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '材料成本',
                'verbose_name_plural': '材料成本',
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整')], max_length=10, verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='变动时间')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='关联单号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='库位')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.materialbatch', verbose_name='批次')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='材料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialmovements', to='inventory.materialpurchase', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '材料变动',
                'verbose_name_plural': '材料变动',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='变动时间')),
                ('reference_number', models.CharField(max_length=50, verbose_name='关联单号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品变动',
                'verbose_name_plural': '产品变动',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='materialpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier', verbose_name='供应商'),
        ),
        migrations.CreateModel(
            name='InventoryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2025-01-01', verbose_name='统计日期')),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='期初库存')),
                ('incoming', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='入库量')),
                ('outgoing', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出库量')),
                ('closing_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='期末库存')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '库存统计',
                'verbose_name_plural': '库存统计',
                'unique_together': {('date', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50, verbose_name='管制编号')),
                ('specification', models.CharField(max_length=100, verbose_name='规格尺寸')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='已入库数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('material_type', models.CharField(default='平板料', max_length=20, verbose_name='采料方式')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='材料')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialpurchase', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
                'unique_together': {('purchase', 'material')},
            },
        ),
    ]
