# Generated by Django 5.1.6 on 2025-03-04 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_number', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('outbound_date', models.DateField(default=django.utils.timezone.now, verbose_name='出库日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_outbounds', to='orders.order', verbose_name='客户订单')),
            ],
            options={
                'verbose_name': '产品出库单',
                'verbose_name_plural': '产品出库单',
                'ordering': ['-outbound_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductOutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productoutbound', verbose_name='出库单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '出库单明细',
                'verbose_name_plural': '出库单明细',
                'unique_together': {('outbound', 'product')},
            },
        ),
    ]
