# Generated by Django 5.1.6 on 2025-03-04 11:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productoutbound_productoutbounditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='单重(kg)'),
        ),
    ]
