# Generated by Django 5.1.6 on 2025-03-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_unit_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_weight',
        ),
    ]
