# Generated by Django 5.1.6 on 2025-06-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_product_unit_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoutbound",
            name="outbound_number",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="出库单号"
            ),
        ),
    ]
