# Generated by Django 5.1.6 on 2025-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_productoutbound_outbound_number"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customers",
            field=models.ManyToManyField(
                blank=True,
                help_text="选择该产品关联的客户",
                to="orders.customer",
                verbose_name="关联客户",
            ),
        ),
    ]
