# Generated by Django 5.1.6 on 2025-06-29 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_product_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_weight",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="产品单件重量，用于计算材料需求量",
                max_digits=10,
                verbose_name="单重(kg)",
            ),
        ),
    ]
